crds:
  install: true
global:
  domain: argo.cch.com
  logging:
    format: json
    level: info

configs:
  cm:
    create: true
    exec.enabled: true
    admin.enabled: true
    statusbadge.enabled: true
    exec.shells: "bash,sh"
    accounts.devuser: login
    accounts.pmuser: login
    accounts.opsuser: login
    accounts.devuser1: login
    accounts.devuser1.enabled: "false"
  params:
    create: true
    otlp.address: ''
    server.insecure: false
    server.basehref: /argocd
    server.rootpath: '/argocd'
    server.staticassets: /shared/app
    server.disable.auth: false
    server.enable.gzip: true
    server.x.frame.options: sameorigin
    # -- Enables [Applications in any namespace]
    application.namespaces: team-*
  rbac:
    create: true
    policy.default: role:readonly
    policy.csv: |
      p, role:dev, applications, get,  team-a-project/simple-app, allow
      p, role:dev, applications, *,  team-b-project/team-b/*, allow
      p, role:dev, projects, get,  team-a-project, allow
      p, role:dev, repositories, get,  *, allow
      p, role:dev, clusters, get,  *, allow
      g, devuser, role:dev
      
      p, role:pm, applications, get,  */*, allow
      p, role:pm, projects, get,  *, allow
      p, role:pm, repositories, get,  *, allow
      p, role:pm, clusters, get,  *, allow
      g, pmuser, role:pm

      p, role:op, applications, *,  */*, allow
      p, role:op, projects, *,  *, allow
      p, role:op, repositories, *,  *, allow
      p, role:op, clusters, *,  *, allow
      p, role:op, accounts, *,  *, allow
      p, role:op, certificates, *,  *, allow
      p, role:op, gpgkeys, *,  *, allow
      p, role:op, exec, create, */*, allow
      g, opsuser, role:op

    scopes: "[groups]"
    policy.matchMode: "glob"

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1
  extensions:
    # -- Enable support for Argo CD extensions
    enabled: false
    extensionList: []
    #  - name: extension-metrics
    #    env:
    #      - name: EXTENSION_URL
    #        value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
    #      - name: EXTENSION_CHECKSUM_URL
    #        value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension_checksums.txt
  certificate:
    enabled: false

  # TLS certificate configuration via Secret
  ingress:
    enabled: true
    ingressClassName: "nginx"
    paths:
      - /argocd
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: argocd-secret # # do not change, this is provided by Argo CD
        hosts:
          - argo.cch.com
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 1